version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      docusaurus:
        patterns:
          - "@docusaurus/*"
      mdx:
        patterns:
          - "@mdx-js/*"
      remark-rehype:
        patterns:
          - "remark-*"
          - "rehype-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
